name: Verify master PR's that are ready for review
on:
  pull_request:
    branches:
      - "master"
    types: [opened, synchronize, ready_for_review]
    paths-ignore:
      - "**/*.md"
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      # checkout repo
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0
        with:
          fetch-depth: 1
      # set up npm
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # 5.0.0
        with:
          node-version: 24
          cache: yarn
      # install deps
      - run: yarn install
      # typechecking
      - run: yarn typecheck
      # run build
      - run: yarn build
